---
? ''
: octodns:
    cloudflare:
      proxied: true
  type: A
  value: 185.199.108.153
_github-challenge-keltermoore:
  type: TXT
  value: 11ef3f321f
_github-challenge-keltermoore.www:
  type: TXT
  value: 7120ae09f9
plants:
  octodns:
    cloudflare:
      proxied: false
  type: CNAME
  value: kondwani.parkermakes.tools.
www:
  octodns:
    cloudflare:
      proxied: false
  type: CNAME
  value: parkr.github.io.
