---
? ''
: - octodns:
      cloudflare:
        proxied: true
    type: A
    value: 217.70.184.38
  - type: MX
    values:
    - exchange: spool.mail.gandi.net.
      preference: 10
    - exchange: fb.mail.gandi.net.
      preference: 50
  - type: TXT
    value: v=spf1 include:_mailcust.gandi.net ?all
blog:
  octodns:
    cloudflare:
      proxied: true
  type: CNAME
  value: blogs.vip.gandi.net.
webmail:
  octodns:
    cloudflare:
      proxied: false
  type: CNAME
  value: webmail.gandi.net.
www:
  octodns:
    cloudflare:
      proxied: true
  type: CNAME
  value: webredir.vip.gandi.net.
zzz:
  octodns:
    cloudflare:
      proxied: false
  type: A
  value: 1.1.1.1
