---
? ''
: octodns:
    cloudflare:
      proxied: false
  type: ALIAS
  value: kruffudd.parkermakes.tools.
'*':
  octodns:
    cloudflare:
      proxied: false
  type: CNAME
  value: parker.codes.
www:
  octodns:
    cloudflare:
      proxied: false
  type: CNAME
  value: parker.codes.
