---
? ''
: - octodns:
      cloudflare:
        proxied: true
    type: ALIAS
    value: kondwani.parkermakes.tools.
  - type: MX
    values:
    - exchange: mxa.mailgun.org.
      preference: 10
    - exchange: mxb.mailgun.org.
      preference: 10
  - type: TXT
    value: v=spf1 include:mailgun.org ~all
'*':
  octodns:
    cloudflare:
      proxied: false
  type: CNAME
  value: parkermakes.tools.
_acme-challenge.baymax:
  type: TXT
  value: TpGzb4WdgOEmz_AY9UbPdH5dYUvYsYXrc5usWcTKVoA
baymax:
  octodns:
    cloudflare:
      proxied: false
  type: A
  value: 10.0.1.14
delwyn:
  octodns:
    cloudflare:
      proxied: false
  type: A
  value: 10.0.1.4
email:
  octodns:
    cloudflare:
      proxied: true
  type: CNAME
  value: mailgun.org.
fluffball:
- octodns:
    cloudflare:
      proxied: false
  type: A
  value: 108.44.153.67
humans:
  octodns:
    cloudflare:
      proxied: false
  type: CNAME
  value: baymax.parkermakes.tools.
kagiso:
- octodns:
    cloudflare:
      proxied: false
  type: A
  value: 104.237.132.31
- octodns:
    cloudflare:
      proxied: false
  type: AAAA
  value: 2600:3c00::f03c:91ff:fefa:5414
kondwani:
- octodns:
    cloudflare:
      proxied: false
  type: A
  value: 172.104.19.218
- octodns:
    cloudflare:
      proxied: false
  type: AAAA
  value: 2600:3c03::f03c:91ff:fe38:7d43
mailo._domainkey:
  type: TXT
  value: k=rsa\; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDJn9zyOB7wJpYT9INfMOBTv9jys6F6dEFz7yLf9uWiRZE3hPdTkf5xbH+CE9ofKyWAvS7oVl/0Ic7xN27ui4F8aUrTH4IGuqO3qpaGP4Ev0braWfQAlk69nJC/wsto6uFS5pZoWgEhJfP3gxs2OXKunFR17s8IWUYfAoBsJ14ACwIDAQAB
pie:
  octodns:
    cloudflare:
      proxied: false
  type: A
  value: 10.0.1.19
radar:
  octodns:
    cloudflare:
      proxied: false
  type: CNAME
  value: kondwani.parkermakes.tools.
rbspy:
  octodns:
    cloudflare:
      proxied: false
  type: CNAME
  value: kondwani.parkermakes.tools.
sylvester:
- octodns:
    cloudflare:
      proxied: false
  type: A
  value: 104.130.13.87
- octodns:
    cloudflare:
      proxied: false
  type: AAAA
  value: 2001:4802:7803:104:be76:4eff:fe20:2449
www:
  octodns:
    cloudflare:
      proxied: true
  type: CNAME
  value: parkermakes.tools.
