---
? ''
: - ttl: 1
    type: ALIAS
    value: kondwani.parkermakes.tools.
  - ttl: 1
    type: MX
    values:
    - exchange: mxa.mailgun.org.
      preference: 10
    - exchange: mxb.mailgun.org.
      preference: 10
  - ttl: 1
    type: TXT
    value: v=spf1 include:mailgun.org ~all
'*':
  ttl: 1
  type: CNAME
  value: parkermakes.tools.
email:
  ttl: 1
  type: CNAME
  value: mailgun.org.
kagiso:
- ttl: 1
  type: A
  value: 104.237.132.31
- ttl: 1
  type: AAAA
  value: 2600:3c00::f03c:91ff:fefa:5414
kondwani:
- ttl: 1
  type: A
  value: 172.104.19.218
- ttl: 1
  type: AAAA
  value: 2600:3c03::f03c:91ff:fe38:7d43
mailo._domainkey:
  ttl: 1
  type: TXT
  value: k=rsa\; p=MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDJn9zyOB7wJpYT9INfMOBTv9jys6F6dEFz7yLf9uWiRZE3hPdTkf5xbH+CE9ofKyWAvS7oVl/0Ic7xN27ui4F8aUrTH4IGuqO3qpaGP4Ev0braWfQAlk69nJC/wsto6uFS5pZoWgEhJfP3gxs2OXKunFR17s8IWUYfAoBsJ14ACwIDAQAB
radar:
  ttl: 1
  type: CNAME
  value: kondwani.parkermakes.tools.
rbspy:
  ttl: 1
  type: CNAME
  value: kondwani.parkermakes.tools.
sylvester:
- ttl: 1
  type: A
  value: 104.130.13.87
- ttl: 1
  type: AAAA
  value: 2001:4802:7803:104:be76:4eff:fe20:2449
www:
  ttl: 1
  type: CNAME
  value: parkermakes.tools.
