---
? ''
: - octodns:
      cloudflare:
        proxied: false
    type: ALIAS
    value: parkr.github.io.
www:
  octodns:
    cloudflare:
      proxied: false
  type: CNAME
  value: parkr.github.io.
