on:
  push:
    branches:
      - main
      - github-actions

name: Deploy on push
jobs:
  deployOnPush:
    name: octodns sync
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: octodns sync
      uses: docker://parkr/octodns:v0.9.10
      env:
        CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}
        CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
      with:
        args: octodns-sync --config-file ./config/production.yaml --doit
